<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec.*.js</string>
		<string>spec.js</string>
		<string>spec</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(before|before_each|after|describe|it)</string>
	<key>foldingStopMarker</key>
	<string>^\s*end$</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JSpec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(before|before_each|after|end)\b</string>
			<key>name</key>
			<string>keyword.other.jspec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#suite</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#spec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>spec</key>
		<dict>
			<key>begin</key>
			<string>^\s*(it)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.jspec.spec</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.jspec.spec</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>suite</key>
		<dict>
			<key>begin</key>
			<string>^\s*(describe)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.jspec.suite</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.jspec.suite</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.jspec</string>
	<key>uuid</key>
	<string>6128E8E5-E65C-4E60-975B-67991C0E6D6D</string>
</dict>
</plist>
